name: ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'

      - name: Build & Test
        run: |
          go mod download
          go build .
          go test ./...

